# Generated by Django 3.2 on 2021-12-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercashflow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='requestcashflow',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.request', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='requestcashflow',
            name='tx_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.requestcashtransactiontype', verbose_name='Тип транзакции'),
        ),
        migrations.AddField(
            model_name='request',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='lot',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='lot',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.request', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='lot',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller', to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='james',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.request', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='james',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Инвестор'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.request', verbose_name='Запрос'),
        ),
        migrations.AddField(
            model_name='companyaccounting',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.company', verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Представитель/Владелец'),
        ),
    ]
