# Generated by Django 3.2 on 2021-12-11 14:34

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Номер телефона', max_length=128, region=None, unique=True)),
                ('password', models.CharField(max_length=300, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('passport_serial', models.CharField(max_length=4, null=True, verbose_name='Серия паспорта')),
                ('passport_num', models.CharField(max_length=6, null=True, verbose_name='Номер паспорта')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Верифицирован?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Модератор?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперпользователь?')),
                ('last_login', models.DateTimeField(null=True, verbose_name='Время последнего входа')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'users',
                'ordering': ['phone'],
            },
        ),
    ]
